### ISSUE TITLE
Building from source

### ISSUE THREAD

**Issue by uwgeophys** [PAMGuard/PAMGuard#42]
Hello,

I wonder if you can help, it appears that the geomajas link in the POM file is down.
Do you know of an alternative @douggillespie ?

I am trying to build a version that has the command/udp function to work with; and it appears the latest release version doesn't, it was fixed a few months after according to the commits.

That or can we get release of a new version posted?

Thank you,

**Comment by douggillespie** [comment]
Hi, 
I was also having trouble with Maven yesterday, but didn't have time to investigate to see which package was causing problems. It seems OK now. However, I checked the usage of geomajas and it doesn't seem to be used anywhere, so I suggest you:
a) try another Maven update and see if the problem is resolved
b) remove that repo from the pom.xml file. I'll do the same on the main branch sometime soon. 
Douglas.
